eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 501954549389-gdeprba69g9ito89iuc5e3tlanrv68i2.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
server:
  port: 8004